### ISSUE TITLE
"Copied" is not working on ubuntu (at least 16.04 lts) 

### ISSUE THREAD

**Issue by juliomatcom** [watilde/emoji-cli#12]
Hello, and thanks for this package.

When I get an emoji ie:
```shell
$ emoji cu
(To exit, press ^C or choose ".exit")
Copied 🇨🇺
```
**it do not get copied to my clipboard**, so I need to select the emoji manually and copy it.

Thanks again.

**Comment by watilde** [comment]
Hello! Thanks for your report. I guess it comes from the module `copy-paste` that is not the latest version. I will bump the version of the modules, and ship it then.

**Comment by watilde** [comment]
Shipped as v0.3.2 right now. Could you please check it, and open this issue again if it's not fixed...? 
Thanks :)

**Comment by juliomatcom** [comment]
```
npm update -g emoji-cli
/home/juliomatcom/.nvm/versions/node/v6.9.4/bin/emoji -> /home/juliomatcom/.nvm/versions/node/v6.9.4/lib/node_modules/emoji-cli/bin/emoji-cli.js
- exit-hook@1.1.1 node_modules/emoji-cli/node_modules/exit-hook
- readline2@1.0.1 node_modules/emoji-cli/node_modules/readline2
- rx-lite@3.1.2 node_modules/emoji-cli/node_modules/rx-lite
- wrappy@1.0.2 node_modules/emoji-cli/node_modules/wrappy
- once@1.4.0 node_modules/emoji-cli/node_modules/once
/home/juliomatcom/.nvm/versions/node/v6.9.4/lib
└── emoji-cli@0.3.2 
```

and still not working buddy :( seems the package `copy-paste` keeps outdated, anyway I will look at the source and try to make a PR later, if the problem remains.

**Comment by watilde** [comment]
Sorry to see that 😢 
Ok thanks! Let me know if you find anything.

**Comment by juliomatcom** [comment]
Ok is working now :see_no_evil: the package is fine, just need to install `xclip` as the documentation in https://github.com/xavi-/node-copy-paste says, and now is working ok, may be you can add in the Readme a reminder about this requirements...

> ... It does this by wrapping pbcopy/pbpaste (for OSX), xclip (for Linux, FreeBSD, and OpenBSD), and clip (for Windows). 

thank you :wink:

**Comment by watilde** [comment]
Ahh I also missed that part! Well, happy to hear that it's working now :)
Thanks!
